server:
  address: ":8000"
  upload_dir: "uploads"
  cover_file_max_size: 10485760 # 10MB
  image_file_max_size: 52428800 # 50MB

database:
  mysql:
    link: ""  # 仅当不为空时使用
    user: "mysql"
    password: "aaa"
    address: "database:3306"
    dbname: "gdev_demo"
  redis:
    addr: "redis:6379"
    password: ""
    DB: 0
