services:
  web:
    build:
      context: ../../
      dockerfile: manifest/docker/Dockerfile
    container_name: "web-gdd"
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - "redis"
      - "database"
    networks:
      - net_gdd

  redis:
    image: "redis:latest"
    container_name: "redis"
    networks:
        - net_gdd
  #    ports:
  #      - ""

  database:
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "aaa"
      MYSQL_DATABASE: "gdev_demo"
      MYSQL_ROOT_PASSWORD: "aaa"
    image: "mysql:latest"
    container_name: "db-mysql"
#    ports:
#      - "3307:3306"
    volumes:
      - "../../resource/database/create/gdev_demo.sql:/docker-entrypoint-initdb.d/db.sql"
    networks:
      - net_gdd
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  net_gdd:
    driver: "bridge"
